kind: pipeline
name: default
steps:
  - name: build
    image: rust:1.61.0
    commands:
      - cargo build --all
  - name: publish
    commands:
      - cargo publish --token
    when:
      event:
        - tag